name: fitnessgrafanashelf
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  shelf: ^1.4.1
  postgres: ^3.1.2
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5
  csv: ^6.0.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
